version: "3"

services:
  flask-app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: 'flask-renee'
    env_file:
      - .env
    volumes:
      - .:/application
    ports:
      - "9191:9191"
    networks:
      - app

networks:
  app:
    driver: bridge
