version: "3"

services:
  flask-app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: 'flask1'
    volumes:
      - .:/application
    ports:
      - "9090:9090"
    networks:
      - app

networks:
  app:
    driver: bridge
