version: "3"

services:
  app4:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: 'renee-montoya4'
    env_file:
      - .env
    volumes:
      - .:/application
    ports:
      - "9494:9494"
    networks:
      - app


networks:
  app:
    driver: bridge
