version: "3"

services:
  app9:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: 'renee-montoya-app9'
    env_file:
      - .env
    volumes:
      - .:/application
    expose:
      - "5000"
    networks:
      - app
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "1337:80"
    depends_on:
      - app9

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
    networks:
      - app
    volumes:
      - db_data:/var/lib/mysql

networks:
  app:
    driver: bridge

volumes:
  db_data:
