version: "3"

services:
  app8:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: 'renee-montoya-app8'
    env_file:
      - .env
    volumes:
      - .:/application
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
    networks:
      - app
    volumes:
      - db_data:/var/lib/mysql

networks:
  app:
    driver: bridge

volumes:
  db_data:
