"""empty message

Revision ID: 437035688554
Revises: e16491884fcb
Create Date: 2021-11-17 23:46:54.726155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437035688554'
down_revision = 'e16491884fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('director_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plants', 'employees', ['director_id'], ['id'])
    op.add_column('salons', sa.Column('address', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salons', 'address')
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.drop_column('plants', 'director_id')
    # ### end Alembic commands ###
