"""empty message

Revision ID: beb247bea617
Revises: 
Create Date: 2021-11-17 22:18:04.789236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'beb247bea617'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plants_ibfk_1', 'plants', type_='foreignkey')
    op.drop_column('plants', 'director_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('director_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('plants_ibfk_1', 'plants', 'employees', ['director_id'], ['id'])
    # ### end Alembic commands ###
