"""empty message

Revision ID: e16491884fcb
Revises: 81b28c454107
Create Date: 2021-11-17 23:37:27.097354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e16491884fcb'
down_revision = '81b28c454107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plants_ibfk_1', 'plants', type_='foreignkey')
    op.drop_column('plants', 'director_id')
    op.drop_column('salons', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('address', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('plants', sa.Column('director_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('plants_ibfk_1', 'plants', 'employees', ['director_id'], ['id'])
    # ### end Alembic commands ###
