version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: 'flask-renee3'
    env_file:
      - .env
    volumes:
      - .:/application
    ports:
      - "9292:9292"
    networks:
      - app


networks:
  app:
    driver: bridge
